### PR TITLE
[Feature]arrange the social media icons

### PR DESCRIPTION
**Pull request by MuthomiMate**
#### What does this PR do
Arranges the social  media icons
#### Description of Task to be completed?
Social media icons needed to be arranged in a better way so that they can cover the whole login block.
#### How should this be manually tested?
Run python manage.py runserver open the login page on your browser.
#### Screenshots 
image

### CODE REVIEW

**Comment by Sharonsyra** [comment]
@MuthomiMate are you all done?

**Comment by MuthomiMate** [comment]
Let me add the credentials to an environment variable so that we can be able to add them on heroku

**Comment by kimotho-njoki** [comment]
Good job with the UI.

**Comment by Sharonsyra** [comment]
Please be keen on merge conflicts @MuthomiMate

**Comment by MuthomiMate** [comment]
@Sharonsyra all good now

**Pull request merged**
