### PR TITLE
#152919313 Chore - flake8 styling fixes

### PR DESCRIPTION
**Pull request by VincentHokie**
#### What does this PR do?
It removes *most* of the flake8 errors from the wger project.

#### Description of Task to be completed?
Editing python files to follow the flake8 code style conventions.

#### How should this be manually tested?
With all the dependancies instlled, execute 
`flake8 wger/ > flake8_errors.txt` on the *develop* branch
then switch to the *ch-flake8-styling-fixes-152919313*  branch and run `flake8 wger/ > flake8_2_errors.txt`.
The flake8_2_errors.txt will have a alot less errors that the flake8_errors.txt file.

Migration folders, the settings file, function based imports, poor variable names and lines that passed the 80 character threshold because of holding a url have been ignored.

#### What are the relevant pivotal tracker stories?
Pivotal Tracker story ID: 152919313

### CODE REVIEW

**Comment by Sharonsyra** [comment]
Did you run flake8 on your end? I am seeing a lot of errors after pulling your branch. Is there a reason for this? @VincentHokie

**Comment by Sharonsyra** [comment]
screen shot 2017-11-22 at 16 32 53

@VincentHokie I still see errors that could be fixed.

**Comment by VincentHokie** [comment]
@Sharonsyra  I ran my flake8 on the wger folder only with `flake8 wger/` as that's where all the custom code is.

**Comment by Sharonsyra** [comment]
But it doesn't specify what folder needs fixing. At the same time would you consider having a .flake8 file for the ones that really need to be excluded? Also check this tool out https://github.com/google/yapf

**Comment by VincentHokie** [comment]
I'll create a .flake8 today and update you and the PR once its done and working @Sharonsyra

**Comment by VincentHokie** [comment]
@Sharonsyra included a flake8 config file to ignore files as suggested, the .flake8 config file didn't work

**Comment by Sharonsyra** [comment]
Nice work on the integrations. @VincentHokie

**Comment by VincentHokie** [comment]
Thanks, @Sharonsyra. It was a team effort .

**Comment by Sharonsyra** [comment]
Let me know when pep8 is all good.

**Comment by VincentHokie** [comment]
Sure thing.

**Comment by VincentHokie** [comment]
@Sharonsyra should be all good now

**Comment by Sharonsyra** [comment]
./manage.py:14:13: F401 'django' imported but unused

**Comment by Sharonsyra** [comment]
@VincentHokie there is a merge conflict.

**Comment by VincentHokie** [comment]
fixed @Sharonsyra

**Comment by Sharonsyra** [comment]
screen shot 2017-11-24 at 08 33 17

Lastly, @VincentHokie

**Comment by VincentHokie** [comment]
@Sharonsyra i cant seem to see the manage.py error on my end, but the rest should be fine

**Comment by Sharonsyra** [comment]
That's cool why does the merge conflict keep appearing?

**Comment by VincentHokie** [comment]
that's probably because new code is being (has been) merged into develop, @Sharonsyra

**Review by Sharonsyra — APPROVED** [review]
Nice

**Pull request merged**
