### PR TITLE
#152919319 fitbit support

### PR DESCRIPTION
**Pull request by kimotho-njoki**
#### What does this PR do?
Integrates Fitbit support into wger.

#### Description of Task to be completed?
Allow wger to access and load weight data from a users Fitbit account.

#### How should this be manually tested?
Run python ./manage.py runserver to visit the wger application.
While on the dashboard, click on the weight drop down arrow on the top navigation bar then weight overview.
On the weight overview page, click on the options tab then import from Fitbit which will redirect you to the Fitbit login page. Once logged in your weight data, if there's any, will be loaded into wger.

#### What are the relevant pivotal tracker stories?
Pivotal Tracker story ID: 152919319

### CODE REVIEW

**Comment by Sharonsyra** [comment]
Merge conflict @kimotho-njoki

**Comment by kimotho-njoki** [comment]
@Sharonsyra conflict resolved

**Review by Sharonsyra — COMMENTED** [review]
Are migrations supposed to be here? @kimotho-njoki

**Comment by kimotho-njoki** [comment]
@Sharonsyra which migrations exactly?? I'm not understanding your exact question

**Comment by kimotho-njoki** [comment]
But the migrations are needed even for travis to pass.. @Sharonsyra

**Comment by Sharonsyra** [comment]
Noted

**Review by VincentHokie — APPROVED** [review]

**Comment by Sharonsyra** [comment]
@kimotho-njoki let me know when this is working.

**Comment by kimotho-njoki** [comment]
@Sharonsyra  yes yes I will

**Comment by kimotho-njoki** [comment]
@Sharonsyra fitbit is now working perfectly

**Comment by Sharonsyra** [comment]
@kimotho-njoki nice work on this.

**Comment by kimotho-njoki** [comment]
Thank you @Sharonsyra

**Pull request merged**
