### PR TITLE
[Chore] Rework landing page [#152919333]

### PR DESCRIPTION
**Pull request by kawerewagaba**
### What does this PR do?
Rework the landing page.

### Description of Task to be completed?
User needs to be able to understand all features of the product on the landing page before scrolling.

### How should this be manually tested?
Test locally by navigating to this [url]: ```http://127.0.0.1:8000/en/software/features```

### Any background context you want to provide?
Wanted to create **a UI that is so simple, aesthetically appealing, but still so functional**. To accomplish that, I had to completely change most elements on the UI.
I switched around layouts, used more appropriate images and icons, gave call-to-actions more weight, made text more readable, and used more appropriate and/or common language.

### What are the relevant pivotal tracker stories?
PT Story ID: [152919333](https://www.pivotaltracker.com/story/show/152919333)

### Some screenshots:
screen shot 2017-12-12 at 18 56 17
screen shot 2017-12-12 at 18 56 52
screen shot 2017-12-12 at 19 06 31

### CODE REVIEW

**Review by Sharonsyra — COMMENTED** [review]
I like the new landing page.

**Comment by Sharonsyra** [comment]
Check the merge conflict @ckwagaba

**Comment by kawerewagaba** [comment]
Done @Sharonsyra. Thanks.

**Review by Sharonsyra — COMMENTED** [review]
Finally

**Pull request merged**
