### PR TITLE
Ft social logins 152919334

### PR DESCRIPTION
**Pull request by MuthomiMate**
#### What does this PR do?
Allows users to log in using their social media accounts
#### Description of Task to be completed?
Users should be able to login to wger system using their social media accounts which are facebook, twitter and google
#### How should this be manually tested?
Run:
cd home and open .config/wger/setting.py and add the following credentials
SOCIAL_AUTH_URL_NAMESPACE = 'social'

SOCIAL_AUTH_TWITTER_KEY = 'your twtter key'
SOCIAL_AUTH_TWITTER_SECRET = 'your twitter secret'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'google api key'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'google api secret'
SOCIAL_AUTH_FACEBOOK_KEY = 'facebook key'
SOCIAL_AUTH_FACEBOOK_SECRET = 'Facebook secret key'  # App Secret
pip install -r requirements_devel.txt to install new dependencies
then 
python manage.py migrate to enable the social authentications
#### What are the relevant pivotal tracker stories?
#152919334
#### Screenshots 
image

### CODE REVIEW

**Comment by Sharonsyra** [comment]
@MuthomiMate Twitter works but I am getting errors from Google+ and Facebook.

**Comment by MuthomiMate** [comment]
@Sharonsyra you need to logout first before you can login with other social media accounts

**Comment by Sharonsyra** [comment]
I am logged out.

**Comment by Sharonsyra** [comment]
Has this worked on two other machines? @MuthomiMate

**Comment by MuthomiMate** [comment]
Yeah it's working @Sharonsyra

**Comment by Sharonsyra** [comment]
Cool merging it.

**Review by Sharonsyra — APPROVED** [review]
Nice job 👍

**Pull request merged**
